apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: MicroService
  title: Node-Ts - Express-Nest Framework
  description: Node-TS Microservice includes qa, monitoring, security, iac
  tags:
    - k8s
    - lambda
    - nest
    - express
    - security
    - microservice
    - apm

spec:
  owner: warlock.gpl@gmail.com
  type: service
  parameters:
    - title: Metadata
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: |
            Unique name of the component. 
            Ex. "payment-auth-login"
        description:
          title: Description
          type: string
          description: |
            Description of the component. 
            Ex. "Payment Authorization service"
        product:
          title: Product Service Name
          type: string
          description: |
            Product Service Name.
            Ex. "payment"
        client:
          title: Client
          type: string
          description: |
            Cliente Name.
            Ex. "Coca-cola"
        team:
          title: Team Name
          type: string
          description: |
            Team Name.
            Ex. "cloud-team-kubernetes"
        technical_lead:
          title: Team TL
          type: string
          description: |
            Technical Leader Name.
            Ex. "Linux Torvals"
        product_owner:
          title: Team PO
          type: string
          description: |
            Team Product Owner
            Ex. "Richard Stallman"

    - title: Application
      properties:
        uniqueItems: true
        runtime:
          title: Runtime Version
          type: string
          enum:
            - node_18
            - node_16
            - node_14
            - node_12
            - node_10
          enumNames:
            - Node 18
            - Node 16
            - Node 14
            - Node 12
            - Node 10
            
        lang2:
          title: "Lang:"
          type: array
          uniqueItems: true
          items:
            type: string
            enum:
              - Typescript
              - Node
          ui:widget: checkboxes
          
        frame:
          title: "Framework:"
          type: array
          items:
            type: string
            enum:
              - Express
              - Nest
          uniqueItems: true
          ui:widget: checkboxes

            
    - title: Assets
      properties:
        tools:
          title: "Assets / Tools:"
          type: array
          items:
            type: string
            enum:
              - Eslint
              - Prettier
              - Commit Lint
              - Husky
              - Dockerfile
              - Semantic Release
          uniqueItems: true
          ui:widget: checkboxes

            
    - title: Cloud Connectors
      properties:
        aws_snippets:
          title: "Aws Services Snippets:"
          type: array
          items:
            type: string
            enum:
              - Simple Queue Service (SQS) 
              - Simple Notification Service (SNS) 
              - Secret Manager (SSM) 
              - Bucket S3
          uniqueItems: true
          ui:widget: checkboxes

    
    - title: Quality
      properties:
        qa_tools:
          title: "Frameworks:"
          type: array
          items:
            type: string
            enum:
              - Jest
              - Nightwatch (Test Browser)
              - Artillery (Load Stress Test)
          uniqueItems: true
          ui:widget: checkboxes


    - title: Monitoring
      properties:
        apm:
          title: Application Performance Manager (APM)
          type: boolean


    - title: Security
      properties:
        scanner:
          title: Dast
          type: boolean


    - title: Infrastructure
      properties:
        infra:
          title: "Infra"
          type: array
          items:
            type: string
            enum:
              - Terraform
              - Serverless
          uniqueItems: true
          ui:widget: checkboxes


    - title: Deploy
      properties:
        deploy:
          title: "Cloud Services"
          type: array
          items:
            type: string
            enum:
              - Lambda
              - Kubernetes
          uniqueItems: true
          ui:widget: checkboxes

          
    - title: Repository Location
      type: string
      ui:field: RepoUrlPicker
      ui:options:
        allowedHosts:
          - github.com
